name: "Build"

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: sudo apt install -y libasound2-dev libmp3lame-dev zip

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        id: rust

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v${{steps.rust.outputs.cachekey}}-rust

#      - name: Setup SSH
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{ secrets.FREE_LIBRESPOT_PRIVATE_KEY }}

      - run: cargo build --release --all-features

      - name: End
        run: |
          zip -r release.zip /home/runner/work/DownOnSpot/DownOnSpot/target/release

      - name: Peek A Boo
        run: |
          ls /home/runner/work/DownOnSpot/DownOnSpot 
             
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /home/runner/work/DownOnSpot/DownOnSpot/release.zip
          token: ${{ secrets.GH_TOKEN }}
          tag_name: v1.0
        env:
          GITHUB_REPOSITORY: sentinm/DownOnSpot
