name: "Build"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Environment
        run: mkdir -p workdir
        
      - name: Jump in
        run: cd workdir
        
      - name: Install dependencies
        run: sudo apt install -y libasound2-dev libmp3lame-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        id: rust

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v${{steps.rust.outputs.cachekey}}-rust

#      - name: Setup SSH
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{ secrets.FREE_LIBRESPOT_PRIVATE_KEY }}

      - run: cargo build --release --all-features
      
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/debug/DownOnSpot.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
